spring:
  main:
    log-startup-info: true # выводим служебную информацию
    banner-mode: off

spring-quiz:
  report:
    # spring-quiz.report.mode — режим формирования отчёта;
    # может иметь одно из двух значений:
    # verbose — формировать расширенный отчёт
    # concise — формировать сокращённый отчёт
    mode: "concise"